/// <summary>
/// Controls the participant's movement during the online neuroadaptive
/// experiment.
///
/// The script continuously listens for LSL markers generated by the Python
/// real-time classification pipeline and translates them into adaptive
/// movements inside the virtual environment. According to the received
/// commands, the player is smoothly moved between predefined height levels,
/// allowing the virtual exposure intensity to be dynamically adjusted.
///
/// The class also manages experiment start/end notifications, movement
/// cooldowns, and visual/audio feedback presented to the participant.
/// </summary>
using UnityEngine;
using LSL;
using System.Threading;
using System.Collections;
using TMPro;

public class OnlinePlayerControl : MonoBehaviour
{
    private StreamInlet inlet;
    private Thread receiveThread;
    private bool running = true;

    // texts on monitor and sounds
    public TMP_Text messageText;
    public AudioSource audioSource;
    public AudioClip beepSound;
    public float messageDuration = 2f;

    // Shared variable between thread and Unity main thread
    private string latestMarker = null;
    private readonly object markerLock = new object();

    // Duration of the height shifts
    public float movementDuration = 10f;

    // Variables regulating the ongoing movements
    private bool canMove = true;
    private float cooldown = 5f;  // so that the participant remains at least this time on the new level

    // Levels variables
    private int current_level = 0;
    public Transform pointA; // to assign
    public Transform pointB; // to assign
    public Transform pointC; // to assign
    private Vector3 startPoint;
    private Vector3[] levels;
    

    void Start()
    {
        // Getting the start point (level 0)
        startPoint = transform.position;
        // and creating the levels array
        levels = new Vector3[]
        {
            startPoint,
            pointA.position,
            pointB.position,
            pointC.position
        };

        receiveThread = new Thread(ReceiveLoop);
        receiveThread.IsBackground = true;
        receiveThread.Start();
    }

    void ReceiveLoop()
    {
        Debug.Log("Searching for MarkerStream...");

        while (running && inlet == null)
        {
            var results = LSL.LSL.resolve_stream("name", "CommandStream", 1, 1.0);

            if (results.Length > 0)
            {
                inlet = new StreamInlet(results[0]);
                Debug.Log("Connected to MarkerStream.");
            }
        }

        if (inlet == null)
            return;

        string[] sample = new string[1];

        while (running)
        {
            double timestamp = inlet.pull_sample(sample);

            if (timestamp != 0.0)
            {
                lock (markerLock)
                {
                    latestMarker = sample[0];
                }
            }
        }
    }

    void Update()
    {
        string marker = null;

        lock (markerLock)
        {
            if (latestMarker != null)
            {
                marker = latestMarker;
                latestMarker = null;
            }
        }

        if (marker != null)
        {
            HandleMarker(marker);
        }
    }

    void HandleMarker(string marker)
    {
        Debug.Log("Received marker: " + marker);

        switch (marker)
        {
            case "Start_Experiment":
                StartExperiment();
                break;

            case "Go_Up":
                GoUp();
                break;

            case "Go_Down":
                GoDown();
                break;

            case "End_Experiment":
                EndExperiment();
                break;

            default:
                Debug.LogWarning("Unknown marker: " + marker);
                break;
        }
    }

    void GoUp()
    {
        Debug.Log("Executing GoUp()");

        if (!canMove) // if there is not an already ongoing movement
            return;

        if (current_level < levels.Length - 1)
        {
            current_level++;
            StartCoroutine(MoveAndCooldown(levels[current_level]));
        }
        else
        {
            Debug.Log("Already at the highest level.");
        }
    }

    void GoDown()
    {
        Debug.Log("Executing GoDown()");

        if (!canMove) // if there is not an already ongoing movement
            return;

        if (current_level > 0)
        {
            current_level--;
            StartCoroutine(MoveAndCooldown(levels[current_level]));
        }
        else
        {
            Debug.Log("Already at the lowest level.");
        }
    }

    void StartExperiment()
    {
        StartCoroutine(ShowMessage("START"));

        Debug.Log("Experiment Started.");
    }

    void EndExperiment()
    {
        // Stop any ongoing movement
        StopAllCoroutines();
        canMove = false;

        StartCoroutine(ShowMessage("END"));

        Debug.Log("Experiment finished.");
    }
    

    private IEnumerator MoveAndCooldown(Vector3 target)
    {
        canMove = false; // from now on, no new markers are accepted

        yield return StartCoroutine(MoveTo(target)); // movement

        yield return new WaitForSeconds(cooldown);   // stay at level

        canMove = true;  // from now on, new markers are accepted
    }

    private IEnumerator MoveTo(Vector3 targetPosition)
    {   // movement definition, based on starting and final positions and on movement desired duration
        Vector3 initialPosition = transform.position;
        float elapsedTime = 0f;

        while (elapsedTime < movementDuration)
        {
            transform.position = Vector3.Lerp(initialPosition, targetPosition, elapsedTime/movementDuration);
            elapsedTime += Time.deltaTime;
            yield return null;
        }

        transform.position = targetPosition;
    }

    // Show Message on display
    private IEnumerator ShowMessage(string text)
    {
        messageText.text = text;
        messageText.gameObject.SetActive(true);

        if (audioSource && beepSound)
            audioSource.PlayOneShot(beepSound);

        yield return new WaitForSeconds(messageDuration);

        messageText.gameObject.SetActive(false);
    }
}